sudo: false

language: scala
scala:
  - 2.12.10
jdk: openjdk8

script:
  - sbt clean
  - sbt compile test:compile
  - sbt coverage test

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage